### ISSUE TITLE
Demo files

### ISSUE THREAD

**Issue by attia3** [FIDS-UWO/climate#4]
The demo files for scaling produce an error, please provide another working example

**Comment by sohomiitb** [comment]
Probably you have to use older version of the software package. Python and
R both are open source software. So they change their packages almost every
day. Please download old version.
Regards
Sohom

**Comment by pbreach** [comment]
Hi @Attia81, the demo files are only meant to provide an example of how to format the data. They are not a large enough sample to run the change factor scaling methodology in the report, as we are limited with the file size that we can upload. If when using your data you run into an error, feel free to open another issue that includes the specific error message.

Cheers, 
Patrick

**Comment by attia3** [comment]
Hi Patrick, thanks for clarifying this and the good work in the Blue book. I actually work with codes in Python and wanted to use the correct input file format. Anyway, I got the change function working for my files. Now, I want to apply the chnage factor to the future data instead of the observed and thus modified the function to do so, how does this sound to you? Can I apply the change factor scaling to the future instead of the observed?
Best, Ahmed

**Comment by pbreach** [comment]
I'm not sure I follow you regarding applying the change factors to the future climate projections. This methodology is meant for applying future changes in climate projected from the GCMs to the observed data. The reason for this is to mitigate bias from the GCMs and retain the autocorrelation structure of the observed data. 

So with this method you won't necessarily end up with a downscaled future climate series. Instead the final result is the observed data adjusted for projected changes in climate from the GCMs. In our work we applied the change factor method multiple times for different time periods of the future climate series (i.e. years 2035-2064, 2065-2094, etc.) to get a sense of climate change impacts over time. 

I hope this makes sense / answers your question. Please let us know otherwise and best of luck.
